version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: luxjob_postgres
    restart: always
    env_file:
      - .env
    environment:
      TZ: Europe/Luxembourg
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro 



  etl:
    build:
      context: ..
      dockerfile: docker/etl/Dockerfile
    container_name: luxjob_etl
    restart: always
    env_file:
      - ../etl/.env
    depends_on:
      - postgres
    volumes:
      - ../etl:/app/etl  
      - /etc/localtime:/etc/localtime:ro 
    networks:
      - default
    environment:
      - TZ=Europe/Luxembourg

  java-api:
    build:
      context: ..
      dockerfile: docker/luxjobstats-api/Dockerfile
    container_name: luxjob_java_api
    restart: always
    env_file:
      - ../luxjobstats-api/.env.docker
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - default

networks:
  default:
    driver: bridge