name: ETL Automation

on:
  schedule:
    - cron: "0 2 * * *"   # every day 02:00
  workflow_dispatch:      # manual run 

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./etl
        run: pip install -r requirements.txt

      - name: Run ETL
        working-directory: ./etl
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          DATA_URL_1: ${{ secrets.DATA_URL_1 }}
          DATA_DWNLD_URL_1: ${{ secrets.DATA_DWNLD_URL_1 }}
          DATA_URL_2: ${{ secrets.DATA_URL_2 }}
          DATA_DWNLD_URL_2: ${{ secrets.DATA_DWNLD_URL_2 }}
        run: python src/main_etl.py

      - name: Translate Dimensions with DeepL API
        working-directory: ./etl
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}

        run: python src/translate_dims.py
