name: ETL Automation

on:
  schedule:
    - cron: "0 13 * * *"     # Every day at 13:00 UTC
  workflow_dispatch:

jobs:

  prepare_env:
    name: Prepare Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./etl
        run: pip install -r requirements.txt


  run_etl:
    name: Run ETL (Download + Process + Load)
    runs-on: ubuntu-latest
    needs: prepare_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run main ETL
        working-directory: ./etl
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          DATA_URL_1: ${{ secrets.DATA_URL_1 }}
          DATA_DWNLD_URL_1: ${{ secrets.DATA_DWNLD_URL_1 }}
          DATA_URL_2: ${{ secrets.DATA_URL_2 }}
          DATA_DWNLD_URL_2: ${{ secrets.DATA_DWNLD_URL_2 }}
        run: python src/main_etl.py


  translate_dims:
    name: Translate Dimension Tables
    runs-on: ubuntu-latest
    needs: run_etl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Translate Dimensions
        working-directory: ./etl
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: python src/translate_dims.py

  done:
    name: Pipeline Finished
    runs-on: ubuntu-latest
    needs: translate_dims

    steps:
      - name: Final Message
        run: echo "ETL Pipeline Completed Successfully!"
